# Generated by Django 4.0.5 on 2022-06-13 08:46

import adapter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adapter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='image',
            field=models.ImageField(upload_to=adapter.models.upload_to),
        ),
    ]
