# Generated by Django 4.0.5 on 2022-06-15 20:22

import adapter.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adapter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=40)),
                ('image', models.ImageField(upload_to=adapter.models.upload_to)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Basic', max_length=50)),
                ('thumbnails', models.CharField(default='0x0', max_length=10)),
                ('link', models.BooleanField(default=True)),
                ('expiring_links', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
