# Generated by Django 4.0.5 on 2022-06-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adapter', '0002_image_profile_thumbnail_tier_delete_attachment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thumbnail',
            old_name='size',
            new_name='dimension',
        ),
    ]
