# Generated by Django 4.0.5 on 2022-06-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adapter', '0002_image_profile_thumbnail_tier_delete_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='c7af2a9e30487c3f6be8e6367c056c14e364e5e2', max_length=20)),
                ('expire', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
