# Generated by Django 4.0.5 on 2022-06-15 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adapter', '0002_myuser_image_tier_delete_attachment_myuser_tier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tier', to='adapter.tier'),
        ),
    ]
