# Generated by Django 4.0.5 on 2022-06-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adapter', '0003_attachment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='content',
        ),
    ]
