# Generated by Django 4.0.5 on 2022-06-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adapter', '0003_alter_myuser_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
