# Generated by Django 4.0.5 on 2022-06-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adapter', '0004_rename_expire_linktoken_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='expiration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linktoken',
            name='token',
            field=models.CharField(default='b98ff1056169cbe2209fe7d2479cfca90ae775cb', max_length=20),
        ),
    ]
