# Generated by Django 4.0.5 on 2022-06-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adapter', '0005_image_delete_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(default='', max_length=40),
        ),
    ]
