# Generated by Django 4.0.5 on 2022-06-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adapter', '0005_image_expiration_alter_linktoken_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='expiration',
        ),
        migrations.AlterField(
            model_name='linktoken',
            name='token',
            field=models.CharField(default='e16774da94192c97123ede8b277471a9ae8def79', max_length=20),
        ),
    ]
