# Generated by Django 4.0.5 on 2022-06-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adapter', '0006_remove_image_expiration_alter_linktoken_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='f1a63fd1da1c52b4d0d26a369e93a94f9c26a05f', max_length=20)),
                ('expiration', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='LinkToken',
        ),
    ]
