# Generated by Django 4.0.5 on 2022-06-24 13:17

import adapter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adapter', '0007_token_delete_linktoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default=adapter.models.generate_key, max_length=20),
        ),
    ]
